// <auto-generated />
#nullable enable
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Em68030.Properties
{
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode]
    [CompilerGenerated]
    public class Strings
    {
        private static ResourceManager? resourceMan;
        private static CultureInfo? resourceCulture;

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager
        {
            get
            {
                if (resourceMan is null)
                {
                    var temp = new ResourceManager("Em68030.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo? Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string MainWindow_Title => ResourceManager.GetString("MainWindow_Title", resourceCulture) ?? "";

        // File Menu
        public static string Menu_File => ResourceManager.GetString("Menu_File", resourceCulture) ?? "";
        public static string Menu_OpenBinary => ResourceManager.GetString("Menu_OpenBinary", resourceCulture) ?? "";
        public static string Menu_OpenSRecord => ResourceManager.GetString("Menu_OpenSRecord", resourceCulture) ?? "";
        public static string Menu_OpenElf => ResourceManager.GetString("Menu_OpenElf", resourceCulture) ?? "";
        public static string Menu_Exit => ResourceManager.GetString("Menu_Exit", resourceCulture) ?? "";

        // Run Menu
        public static string Menu_Run => ResourceManager.GetString("Menu_Run", resourceCulture) ?? "";
        public static string Menu_RunF5 => ResourceManager.GetString("Menu_RunF5", resourceCulture) ?? "";
        public static string Menu_StopShiftF5 => ResourceManager.GetString("Menu_StopShiftF5", resourceCulture) ?? "";
        public static string Menu_StepF10 => ResourceManager.GetString("Menu_StepF10", resourceCulture) ?? "";
        public static string Menu_RunToCursor => ResourceManager.GetString("Menu_RunToCursor", resourceCulture) ?? "";
        public static string Menu_SetPCToCursor => ResourceManager.GetString("Menu_SetPCToCursor", resourceCulture) ?? "";
        public static string Menu_Reset => ResourceManager.GetString("Menu_Reset", resourceCulture) ?? "";
        public static string Menu_FullReset => ResourceManager.GetString("Menu_FullReset", resourceCulture) ?? "";

        // View Menu
        public static string Menu_View => ResourceManager.GetString("Menu_View", resourceCulture) ?? "";
        public static string Menu_ConsoleWindow => ResourceManager.GetString("Menu_ConsoleWindow", resourceCulture) ?? "";
        public static string Menu_FramebufferWindow => ResourceManager.GetString("Menu_FramebufferWindow", resourceCulture) ?? "";
        public static string Menu_BreakpointsWindow => ResourceManager.GetString("Menu_BreakpointsWindow", resourceCulture) ?? "";
        public static string Menu_ToggleLstView => ResourceManager.GetString("Menu_ToggleLstView", resourceCulture) ?? "";

        // Settings Menu
        public static string Menu_Settings => ResourceManager.GetString("Menu_Settings", resourceCulture) ?? "";
        public static string Menu_EmulatorSettings => ResourceManager.GetString("Menu_EmulatorSettings", resourceCulture) ?? "";

        // Help Menu
        public static string Menu_Help => ResourceManager.GetString("Menu_Help", resourceCulture) ?? "";
        public static string Menu_About => ResourceManager.GetString("Menu_About", resourceCulture) ?? "";

        // Toolbar
        public static string Toolbar_Run => ResourceManager.GetString("Toolbar_Run", resourceCulture) ?? "";
        public static string Toolbar_Stop => ResourceManager.GetString("Toolbar_Stop", resourceCulture) ?? "";
        public static string Toolbar_Step => ResourceManager.GetString("Toolbar_Step", resourceCulture) ?? "";
        public static string Toolbar_Reset => ResourceManager.GetString("Toolbar_Reset", resourceCulture) ?? "";
        public static string Toolbar_FullReset => ResourceManager.GetString("Toolbar_FullReset", resourceCulture) ?? "";
        public static string Toolbar_Trace => ResourceManager.GetString("Toolbar_Trace", resourceCulture) ?? "";

        // Disassembly Pane
        public static string Disasm_Title => ResourceManager.GetString("Disasm_Title", resourceCulture) ?? "";
        public static string Disasm_Address => ResourceManager.GetString("Disasm_Address", resourceCulture) ?? "";
        public static string Disasm_Size => ResourceManager.GetString("Disasm_Size", resourceCulture) ?? "";
        public static string Disasm_Go => ResourceManager.GetString("Disasm_Go", resourceCulture) ?? "";
        public static string Disasm_FollowPC => ResourceManager.GetString("Disasm_FollowPC", resourceCulture) ?? "";
        public static string Disasm_LST => ResourceManager.GetString("Disasm_LST", resourceCulture) ?? "";

        // Registers Pane
        public static string Regs_Title => ResourceManager.GetString("Regs_Title", resourceCulture) ?? "";
        public static string Regs_DataRegisters => ResourceManager.GetString("Regs_DataRegisters", resourceCulture) ?? "";
        public static string Regs_AddressRegisters => ResourceManager.GetString("Regs_AddressRegisters", resourceCulture) ?? "";
        public static string Regs_Flags => ResourceManager.GetString("Regs_Flags", resourceCulture) ?? "";
        public static string Regs_SpecialRegisters => ResourceManager.GetString("Regs_SpecialRegisters", resourceCulture) ?? "";
        public static string Regs_FpuRegisters => ResourceManager.GetString("Regs_FpuRegisters", resourceCulture) ?? "";
        public static string Regs_Edit => ResourceManager.GetString("Regs_Edit", resourceCulture) ?? "";
        public static string Regs_Apply => ResourceManager.GetString("Regs_Apply", resourceCulture) ?? "";
        public static string Regs_Cancel => ResourceManager.GetString("Regs_Cancel", resourceCulture) ?? "";

        // Memory Dump Pane
        public static string MemDump_Title => ResourceManager.GetString("MemDump_Title", resourceCulture) ?? "";
        public static string MemDump_Address => ResourceManager.GetString("MemDump_Address", resourceCulture) ?? "";
        public static string MemDump_Size => ResourceManager.GetString("MemDump_Size", resourceCulture) ?? "";
        public static string MemDump_Go => ResourceManager.GetString("MemDump_Go", resourceCulture) ?? "";
        public static string MemDump_Edit => ResourceManager.GetString("MemDump_Edit", resourceCulture) ?? "";
        public static string MemDump_Apply => ResourceManager.GetString("MemDump_Apply", resourceCulture) ?? "";
        public static string MemDump_Cancel => ResourceManager.GetString("MemDump_Cancel", resourceCulture) ?? "";

        // Context Menu
        public static string Context_Copy => ResourceManager.GetString("Context_Copy", resourceCulture) ?? "";
        public static string Context_RunToCursor => ResourceManager.GetString("Context_RunToCursor", resourceCulture) ?? "";
        public static string Context_SetPCToAddress => ResourceManager.GetString("Context_SetPCToAddress", resourceCulture) ?? "";
        public static string Context_Cancel => ResourceManager.GetString("Context_Cancel", resourceCulture) ?? "";
        public static string Context_Paste => ResourceManager.GetString("Context_Paste", resourceCulture) ?? "";
        public static string Context_SelectAll => ResourceManager.GetString("Context_SelectAll", resourceCulture) ?? "";

        // Status Bar
        public static string Status_Running => ResourceManager.GetString("Status_Running", resourceCulture) ?? "";
        public static string Status_Halted => ResourceManager.GetString("Status_Halted", resourceCulture) ?? "";
        public static string Status_Stopped => ResourceManager.GetString("Status_Stopped", resourceCulture) ?? "";
        public static string Status_NotRunning => ResourceManager.GetString("Status_NotRunning", resourceCulture) ?? "";
        public static string Status_FileNone => ResourceManager.GetString("Status_FileNone", resourceCulture) ?? "";
        public static string Status_FileFormat => ResourceManager.GetString("Status_FileFormat", resourceCulture) ?? "";
        public static string Status_CyclesFormat => ResourceManager.GetString("Status_CyclesFormat", resourceCulture) ?? "";
        public static string Status_MhzFormat => ResourceManager.GetString("Status_MhzFormat", resourceCulture) ?? "";
        public static string Status_AvgMhzFormat => ResourceManager.GetString("Status_AvgMhzFormat", resourceCulture) ?? "";

        // About Dialog
        public static string About_Title => ResourceManager.GetString("About_Title", resourceCulture) ?? "";
        public static string About_Subtitle => ResourceManager.GetString("About_Subtitle", resourceCulture) ?? "";
        public static string About_VersionFormat => ResourceManager.GetString("About_VersionFormat", resourceCulture) ?? "";
        public static string About_BuildFormat => ResourceManager.GetString("About_BuildFormat", resourceCulture) ?? "";
        public static string About_Copyright => ResourceManager.GetString("About_Copyright", resourceCulture) ?? "";
        public static string About_License => ResourceManager.GetString("About_License", resourceCulture) ?? "";

        // Window Titles
        public static string Window_Breakpoints => ResourceManager.GetString("Window_Breakpoints", resourceCulture) ?? "";
        public static string Window_Console => ResourceManager.GetString("Window_Console", resourceCulture) ?? "";
        public static string Window_ConsoleFormat => ResourceManager.GetString("Window_ConsoleFormat", resourceCulture) ?? "";
        public static string Window_Settings => ResourceManager.GetString("Window_Settings", resourceCulture) ?? "";
        public static string Window_Input => ResourceManager.GetString("Window_Input", resourceCulture) ?? "";

        // Breakpoints Window
        public static string Breakpoints_ClearAll => ResourceManager.GetString("Breakpoints_ClearAll", resourceCulture) ?? "";
        public static string Breakpoints_Delete => ResourceManager.GetString("Breakpoints_Delete", resourceCulture) ?? "";

        // Console Window
        public static string Console_Log => ResourceManager.GetString("Console_Log", resourceCulture) ?? "";
        public static string Console_Live => ResourceManager.GetString("Console_Live", resourceCulture) ?? "";
        public static string Console_ToggleTooltip => ResourceManager.GetString("Console_ToggleTooltip", resourceCulture) ?? "";

        // Dialog Buttons
        public static string Dialog_OK => ResourceManager.GetString("Dialog_OK", resourceCulture) ?? "";
        public static string Dialog_Cancel => ResourceManager.GetString("Dialog_Cancel", resourceCulture) ?? "";

        // File Dialogs
        public static string FileDialog_OpenBinary => ResourceManager.GetString("FileDialog_OpenBinary", resourceCulture) ?? "";
        public static string FileDialog_OpenSRecord => ResourceManager.GetString("FileDialog_OpenSRecord", resourceCulture) ?? "";
        public static string FileDialog_OpenElf => ResourceManager.GetString("FileDialog_OpenElf", resourceCulture) ?? "";
        public static string FileDialog_LoadAddress => ResourceManager.GetString("FileDialog_LoadAddress", resourceCulture) ?? "";
        public static string FileDialog_EnterLoadAddress => ResourceManager.GetString("FileDialog_EnterLoadAddress", resourceCulture) ?? "";

        // Messages
        public static string Msg_ElfLoaded => ResourceManager.GetString("Msg_ElfLoaded", resourceCulture) ?? "";
        public static string Msg_ElfLoaderTitle => ResourceManager.GetString("Msg_ElfLoaderTitle", resourceCulture) ?? "";
        public static string Msg_ElfLoaderError => ResourceManager.GetString("Msg_ElfLoaderError", resourceCulture) ?? "";
        public static string Msg_FailedToLoadElf => ResourceManager.GetString("Msg_FailedToLoadElf", resourceCulture) ?? "";
        public static string Msg_LoadError => ResourceManager.GetString("Msg_LoadError", resourceCulture) ?? "";
        public static string Msg_FailedToLoadBinary => ResourceManager.GetString("Msg_FailedToLoadBinary", resourceCulture) ?? "";
        public static string Msg_FailedToLoadSRecord => ResourceManager.GetString("Msg_FailedToLoadSRecord", resourceCulture) ?? "";
        public static string Msg_InvalidHexAddress => ResourceManager.GetString("Msg_InvalidHexAddress", resourceCulture) ?? "";
        public static string Msg_Error => ResourceManager.GetString("Msg_Error", resourceCulture) ?? "";
        public static string Msg_InvalidSize => ResourceManager.GetString("Msg_InvalidSize", resourceCulture) ?? "";
        public static string Msg_Success => ResourceManager.GetString("Msg_Success", resourceCulture) ?? "";

        // Settings Window
        public static string Settings_BoardType => ResourceManager.GetString("Settings_BoardType", resourceCulture) ?? "";
        public static string Settings_Board => ResourceManager.GetString("Settings_Board", resourceCulture) ?? "";
        public static string Settings_Mvme147Settings => ResourceManager.GetString("Settings_Mvme147Settings", resourceCulture) ?? "";
        public static string Settings_RomImage => ResourceManager.GetString("Settings_RomImage", resourceCulture) ?? "";
        public static string Settings_TargetOS => ResourceManager.GetString("Settings_TargetOS", resourceCulture) ?? "";
        public static string Settings_OperatingSystem => ResourceManager.GetString("Settings_OperatingSystem", resourceCulture) ?? "";
        public static string Settings_BootPartition => ResourceManager.GetString("Settings_BootPartition", resourceCulture) ?? "";
        public static string Settings_CommandLine => ResourceManager.GetString("Settings_CommandLine", resourceCulture) ?? "";
        public static string Settings_ScsiDisks => ResourceManager.GetString("Settings_ScsiDisks", resourceCulture) ?? "";
        public static string Settings_ScsiDescription => ResourceManager.GetString("Settings_ScsiDescription", resourceCulture) ?? "";
        public static string Settings_AddDisk => ResourceManager.GetString("Settings_AddDisk", resourceCulture) ?? "";
        public static string Settings_NewImageSizeMB => ResourceManager.GetString("Settings_NewImageSizeMB", resourceCulture) ?? "";
        public static string Settings_Create => ResourceManager.GetString("Settings_Create", resourceCulture) ?? "";
        public static string Settings_ScsiCdRom => ResourceManager.GetString("Settings_ScsiCdRom", resourceCulture) ?? "";
        public static string Settings_IsoImage => ResourceManager.GetString("Settings_IsoImage", resourceCulture) ?? "";
        public static string Settings_ScsiId => ResourceManager.GetString("Settings_ScsiId", resourceCulture) ?? "";
        public static string Settings_Network => ResourceManager.GetString("Settings_Network", resourceCulture) ?? "";
        public static string Settings_NetworkMode => ResourceManager.GetString("Settings_NetworkMode", resourceCulture) ?? "";
        public static string Settings_NetworkVirtual => ResourceManager.GetString("Settings_NetworkVirtual", resourceCulture) ?? "";
        public static string Settings_NetworkNat => ResourceManager.GetString("Settings_NetworkNat", resourceCulture) ?? "";
        public static string Settings_GatewayIP => ResourceManager.GetString("Settings_GatewayIP", resourceCulture) ?? "";
        public static string Settings_GatewayMAC => ResourceManager.GetString("Settings_GatewayMAC", resourceCulture) ?? "";
        public static string Settings_Memory => ResourceManager.GetString("Settings_Memory", resourceCulture) ?? "";
        public static string Settings_MemorySizeMB => ResourceManager.GetString("Settings_MemorySizeMB", resourceCulture) ?? "";
        public static string Settings_MemoryDescription => ResourceManager.GetString("Settings_MemoryDescription", resourceCulture) ?? "";
        public static string Settings_NetworkDescription => ResourceManager.GetString("Settings_NetworkDescription", resourceCulture) ?? "";
        public static string Settings_IoDevices => ResourceManager.GetString("Settings_IoDevices", resourceCulture) ?? "";
        public static string Settings_ConsoleEnabled => ResourceManager.GetString("Settings_ConsoleEnabled", resourceCulture) ?? "";
        public static string Settings_ConsoleBaseAddr => ResourceManager.GetString("Settings_ConsoleBaseAddr", resourceCulture) ?? "";
        public static string Settings_ScrollbackLines => ResourceManager.GetString("Settings_ScrollbackLines", resourceCulture) ?? "";
        public static string Settings_TerminalSize => ResourceManager.GetString("Settings_TerminalSize", resourceCulture) ?? "";
        public static string Settings_HddEnabled => ResourceManager.GetString("Settings_HddEnabled", resourceCulture) ?? "";
        public static string Settings_HddBaseAddr => ResourceManager.GetString("Settings_HddBaseAddr", resourceCulture) ?? "";
        public static string Settings_HddImage => ResourceManager.GetString("Settings_HddImage", resourceCulture) ?? "";
        public static string Settings_ImageFile => ResourceManager.GetString("Settings_ImageFile", resourceCulture) ?? "";
        public static string Settings_Performance => ResourceManager.GetString("Settings_Performance", resourceCulture) ?? "";
        public static string Settings_EnableJit => ResourceManager.GetString("Settings_EnableJit", resourceCulture) ?? "";
        public static string Settings_JitDescription => ResourceManager.GetString("Settings_JitDescription", resourceCulture) ?? "";
        public static string Settings_MinBlockLength => ResourceManager.GetString("Settings_MinBlockLength", resourceCulture) ?? "";
        public static string Settings_CompileThreshold => ResourceManager.GetString("Settings_CompileThreshold", resourceCulture) ?? "";
        public static string Settings_Framebuffer => ResourceManager.GetString("Settings_Framebuffer", resourceCulture) ?? "";
        public static string Settings_EnableFramebuffer => ResourceManager.GetString("Settings_EnableFramebuffer", resourceCulture) ?? "";
        public static string Settings_FramebufferDescription => ResourceManager.GetString("Settings_FramebufferDescription", resourceCulture) ?? "";
        public static string Settings_FbResolution => ResourceManager.GetString("Settings_FbResolution", resourceCulture) ?? "";
        public static string Settings_FbBpp => ResourceManager.GetString("Settings_FbBpp", resourceCulture) ?? "";
        public static string Settings_FbVramBase => ResourceManager.GetString("Settings_FbVramBase", resourceCulture) ?? "";
        public static string Settings_Display => ResourceManager.GetString("Settings_Display", resourceCulture) ?? "";
        public static string Settings_FontFamily => ResourceManager.GetString("Settings_FontFamily", resourceCulture) ?? "";
        public static string Settings_FontSize => ResourceManager.GetString("Settings_FontSize", resourceCulture) ?? "";
        public static string Settings_Browse => ResourceManager.GetString("Settings_Browse", resourceCulture) ?? "";
        public static string Settings_SelectRomImage => ResourceManager.GetString("Settings_SelectRomImage", resourceCulture) ?? "";
        public static string Settings_SelectHddImage => ResourceManager.GetString("Settings_SelectHddImage", resourceCulture) ?? "";
        public static string Settings_SelectScsiDisk => ResourceManager.GetString("Settings_SelectScsiDisk", resourceCulture) ?? "";
        public static string Settings_SelectCdRomIso => ResourceManager.GetString("Settings_SelectCdRomIso", resourceCulture) ?? "";
        public static string Settings_CreateScsiDisk => ResourceManager.GetString("Settings_CreateScsiDisk", resourceCulture) ?? "";
        public static string Settings_CreateHddImage => ResourceManager.GetString("Settings_CreateHddImage", resourceCulture) ?? "";
        public static string Settings_WriteDisklabel => ResourceManager.GetString("Settings_WriteDisklabel", resourceCulture) ?? "";
        public static string Settings_DisklabelConfirm => ResourceManager.GetString("Settings_DisklabelConfirm", resourceCulture) ?? "";
        public static string Settings_Disklabel => ResourceManager.GetString("Settings_Disklabel", resourceCulture) ?? "";
        public static string Settings_CreatedScsiDiskFormat => ResourceManager.GetString("Settings_CreatedScsiDiskFormat", resourceCulture) ?? "";
        public static string Settings_CreatedHddImageFormat => ResourceManager.GetString("Settings_CreatedHddImageFormat", resourceCulture) ?? "";

        // Status Messages
        public static string Status_BreakpointFormat => ResourceManager.GetString("Status_BreakpointFormat", resourceCulture) ?? "";
        public static string Status_InfiniteLoopFormat => ResourceManager.GetString("Status_InfiniteLoopFormat", resourceCulture) ?? "";
        public static string Status_147BugReturn => ResourceManager.GetString("Status_147BugReturn", resourceCulture) ?? "";
        public static string Settings_KernelImage => ResourceManager.GetString("Settings_KernelImage", resourceCulture) ?? "";
        public static string Settings_KernelImageDescription => ResourceManager.GetString("Settings_KernelImageDescription", resourceCulture) ?? "";
        public static string Settings_SelectKernelImage => ResourceManager.GetString("Settings_SelectKernelImage", resourceCulture) ?? "";
        public static string Settings_Debug => ResourceManager.GetString("Settings_Debug", resourceCulture) ?? "";
        public static string Settings_EnableTraceButton => ResourceManager.GetString("Settings_EnableTraceButton", resourceCulture) ?? "";
        public static string Settings_TraceDescription => ResourceManager.GetString("Settings_TraceDescription", resourceCulture) ?? "";
    }
}
